name: Deploy Theme (DEV)
on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  deploy:
    # runs-on: ubuntu-20.04
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.4.1
        with:
          api-url: ${{ secrets.DEV_GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.DEV_GHOST_ADMIN_API_KEY }}
